version: "3.5"

services:
  mongo:
    image: mongo:4
    container_name: mongo
    hostname: mongo
    ports:
      - 27017:27017
    networks:
      - s3-network
    # network_mode: host
    volumes:
      - mongo:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - s3-network
    # network_mode: host
    volumes: 
      - rabbitmq:/var/lib/rabbitmq

  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - s3-network
    # network_mode: host
    volumes: 
      - redis:/data
  
  #consul:
  #  image: consul
  #  container_name: consul
  #  restart: always
  #  ports:
  #    - 8500:8500
  #  networks:
  #    - s3-network
  #  # network_mode: host
  #  volumes:
  #    - consul:/consul/data
  #
  #fabio:
  #  image: fabiolb/fabio
  #  container_name: fabio
  #  restart: always
  #  environment:
  #  - FABIO_REGISTRY_CONSUL_ADDR=consul:8500
  #  networks:
  #    - s3-network
  #  # network_mode: host
  #  ports:
  #  - 9998:9998
  #  - 9999:9999
  #
  #grafana:
  #  image: grafana/grafana
  #  container_name: grafana
  #  restart: always
  #  ports:
  #    - 3000:3000
  #  networks:
  #    - s3-network
  #  # network_mode: host
  #  volumes:
  #    - grafana:/var/lib/grafana
  #
  #influxdb:
  #  image: influxdb
  #  container_name: influxdb
  #  restart: always
  #  ports:
  #    - 8086:8086
  #  networks:
  #    - s3-network
  #  # network_mode: host
  #  volumes:
  #    - influxdb:/var/lib/influxdb
  #
  #jaeger:
  #  image: jaegertracing/all-in-one
  #  container_name: jaeger
  #  restart: always
  #  ports:
  #    - 5775:5775/udp
  #    - 5778:5778
  #    - 6831:6831/udp
  #    - 6832:6832/udp
  #    - 9411:9411
  #    - 14268:14268
  #    - 16686:16686
  #  networks:
  #    - s3-network
  #  # network_mode: host
  #
  #prometheus:
  #  image: prom/prometheus
  #  container_name: prometheus
  #  restart: always
  #  ports:
  #    - '9090:9090'
  #  networks:
  #    - s3-network
  #  # network_mode: host
  #  volumes:
  #    - prometheus:/prometheus
  #    - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
  #
  #seq:
  #  image: datalust/seq 
  #  container_name: seq
  #  restart: always
  #  environment:
  #    - ACCEPT_EULA=Y
  #  ports:
  #    - 5341:80
  #  networks:
  #    - s3-network
  #  # network_mode: host
  #  volumes: 
  #    - seq:/data
  #
  #vault:
  #  image: vault
  #  container_name: vault
  #  restart: always
  #  ports:
  #    - 8200:8200
  #  networks:
  #    - s3-network
  #  # network_mode: host
  #  environment:
  #    - VAULT_ADDR=http://127.0.0.1:8200
  #    - VAULT_DEV_ROOT_TOKEN_ID=secret
  #  cap_add:
  #    - IPC_LOCK


networks:
  s3-network:
    name: s3-network
    driver: bridge
    external: false

volumes:
  mongo:
    driver: local
  rabbitmq:
    driver: local
  redis:
    driver: local
  #consul:
  #  driver: local
  #grafana:
  #  driver: local
  #influxdb:
  #  driver: local
  #prometheus:
  #  driver: local
  #seq:
  #  driver: local