version: "3.5"

services:
  apigateway:
    image: apigateway:1.0
    container_name: apigateway
    restart: always
    ports:
      - 5000:80
      - 5010:443
    networks:
      - s3

  identity:
    image: identity-service:1.0
    container_name: identity-service
    restart: always
    ports:
      - 5001:80 
    networks:
      - s3

  registration:
    image: registration-service:1.0
    container_name: registration-service
    restart: always
    ports:
      - 5002:80 
    networks:
      - s3

 

networks:
  s3:
    name: s3-network
    external: false